### ISSUE TITLE
TypeError: func() takes no keyword arguments

### ISSUE THREAD

**Issue by its-monotype** [dave-msk/merak#10]

**Comment by its-monotype** [comment]
Where to set compiler_directives? How to specify it "always_allow_keywords": True?

**Comment by dave-msk** [comment]
Please provide how the problem can be reproduced

**Comment by its-monotype** [comment]
@dave-msk https://stackoverflow.com/questions/68380123/cythonized-function-with-a-single-positional-argument-is-not-possible-to-call-us

**Comment by its-monotype** [comment]
@dave-msk

**Comment by dave-msk** [comment]
The fix looks good to me. However, the company I'm working for has some restrictions on open-source project participation. I am still waiting for approval from my employer to let me update the project, so there will be some time before I'm able to make changes
