### ISSUE TITLE
__pycache__ is not ignored

### ISSUE THREAD

**Issue by rtommy** [dave-msk/merak#20]
The binary package built with 0.3.3.1 includes all the `__pycache__` folder from the original python package (e.g. the original package was copied from `Lib\\site-packages` which has `__pycache__` already after that package was used at least once).

Should not be all the `__pycache__` folders ignored and not copied into the binary package output folder?

**Comment by dave-msk** [comment]
The input package is expected to be distribution-ready. Therefore, it is assumed that everything within is to be preserved.

We do not attempt to decide which kind of file is to be filtered/ignored as this should be a user decision, and the possibility is virtually unlimited. There might be times an `.idea/` folder, or other caches such as `.DS_Store` files, that might need to be excluded. The decision is therefore made not to introduce a filter and such control on which file to be included is returned to the user

If you do want to clean up the pycache files, here's a bash command that you might find handy

```bash
find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
```
