### ISSUE TITLE
module 'foo' has no attribute 'baz'

### ISSUE THREAD

**Issue by liukangcc** [dave-msk/merak#3]
![image](https://user-images.githubusercontent.com/44889940/125910907-8a8d6aed-8b42-42f4-ae19-e0ce33dd3694.png)

use cmd `merak cythonize examples/foo foo-build` to generate .so file, but the .so file can't run when i import it:

![image](https://user-images.githubusercontent.com/44889940/125911170-55e1123e-1ffc-4cc5-8337-ecc5f2b25ed0.png)

the .so file name is not normal.What details have I lost?

![image](https://user-images.githubusercontent.com/44889940/125919540-09072b40-9f5c-4c87-b7b5-94a0176afaba.png)

**Comment by dave-msk** [comment]
Could you paste the screenshot of your terminal when you encounter the error?

**Comment by liukangcc** [comment]
> Could you paste the screenshot of your terminal when you encounter the error?

It's working just fine, thank you
