### ISSUE TITLE
Module Flattening may break relative imports

### ISSUE THREAD

**Issue by W-Yuhao** [dave-msk/merak#8]
# Issue Description:
My project have such structure.
```python
foo/
  |- bar/
  |  |- __init__.py
  |  |- core.py
  |- __init__.py
  |- constant.py
```

Inside `foo.bar.core`, I have a relative import to the `foo.constant` as below.
```python
from ..constant import some_thing
```

It seems like the module flatten will not modify the relative imports to the correct level which cause
```python
ValueError: attempted relative import beyond top-level package
```
when trying to import foo.bar.core using complied library.

Using absolute imports solves the problem with no issue.
```python
from foo.constant import some_thing
```

I know it is not a good design pattern, and it will be good to support it.

# Possible remedy:
- Always transform the relative imports to absolute imports before flatten

**Comment by dave-msk** [comment]
Well, this tool was developed with absolute imports in mind. I'll try and see if it's possible to do the transformation

**Comment by dave-msk** [comment]
Added support for relative imports. Please upgrade to `v0.3.0` to use it

**Comment by W-Yuhao** [comment]
Thank you for the quick update!
