### ISSUE TITLE
Can't be resolved relative to the current directory.

### ISSUE THREAD

**Issue by AbdelsalamHaa** [dave-msk/merak#9]
I'm trying to use your too, but it seems like got an issue with the way I run it. 

I have a package that contains other packages and modules. The formate of my project is like following

--projectName 
---package_name
------subpakage1
---------module2
------subpakage2
---------module2
------subpakage3
---------module2
-----module1

So I run the following command

merak cythonize ./package_name built_backage

but I get the following error

ValueError: C:\Users\ABDELS~1\AppData\Local\Temp\tmpic3t6kta\Applications\subpakage1\__init__.py can't be resolved relative to the current directory.
Either run absolufy-imports from the project root, or pass
--application-directories

I'm not sure how to fix that. I hope you can help. 

Note: I'm using Windows with python 3.8 

Thanks a lot

**Comment by dave-msk** [comment]
I don't have access to any Windows machine right now. If anyone has found a fix please submit a PR

**Comment by dave-msk** [comment]
I believe this is fixed in the recent bug fix. Please upgrade to v0.3.3.2 and try again
